# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache

    # At the moment, sbt 0.13.5 is preinstalled in Travis VM image,
    # which fortunately corresponds to current scalaz settings.
    # The line below can be used to cache a given sbt version.
    # - $HOME/.sbt/launchers/0.13.x

    # At the moment, Scala 2.11.2 and 2.10.4 are preinstalled in Travis VM
    # image, which fortunately corresponds to current scalaz settings.
    # The line below is used to cache the scala version used by the build
    # job, as these versions might be replaced after a Travis CI build
    # environment upgrade (e.g. scala 2.11.2 could be replaced by scala 2.11.4).
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

language: scala
scala:
  - 2.12.0-M5
  - 2.11.8
  - 2.10.6
jdk:
  - oraclejdk8 # scalaz 7.3 does not support Java 7

script:
  - git config core.whitespace tab-in-indent,trailing-space,blank-at-eol
  - git show --oneline --check
  # https://github.com/non/kind-projector/issues/28
  - if [[ "${TRAVIS_SCALA_VERSION}" == "2.12.0-M5" ]]; then git clone https://github.com/non/kind-projector.git && cd kind-projector && git checkout v0.8.0 && echo "sbt.version=0.13.11" > project/build.properties && sbt '++ 2.12.0-M5' publishLocal && cd .. ; fi
  - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3784m check-gen-type-classes "project $TEST_PROJECT" test:compile
  - sbt ++$TRAVIS_SCALA_VERSION "project $TEST_PROJECT" test "project /" $(if [[ "${TEST_PROJECT}" == "rootJVM" ]]; then echo "publishLocal"; fi)
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

env:
  matrix:
  - TEST_PROJECT="rootJVM"
  - TEST_PROJECT="rootJS"

addons:
  apt:
    packages:
      - oracle-java8-installer
