---
# Remove cli_conf_dir.

- name: remove cli config directory
  file:
    path: "{{ go_cli_conf_dir }}"
    state: absent
  become: true

- name: remove go cli nginx directory
  file:
    path: "{{ go_cli_nginx_dir }}"
    state: absent
  become: true
