---
# This playbook deploys an Openwhisk stack.
# It assumes you have already set up your database with the respective db provider playbook (currently cloudant.yml or couchdb.yml)

- include: wipe.yml

- include: consul.yml

- include: kafka.yml

- include: controller.yml

- include: invoker.yml

- include: edge.yml

- include: postdeploy.yml
