---
# This playbook installs additional packages after whisk has been deployed.

- include: properties.yml

- hosts: ansible
  tasks:
    - include: tasks/installCatalog.yml
      when: mode == "deploy"