sudo: false
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.7
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
script:
  - sbt clean coverage doc assembly
before_script: # the automated download fails sometimes
    - mkdir -p $HOME/.sbt/launchers/0.13.8/
    - test -r $HOME/.sbt/launchers/0.13.8/sbt-launch.jar || curl -L -o $HOME/.sbt/launchers/0.13.8/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
after_success:
  - sbt coverageReport coveralls
notifications:
  slack:
    secure: apUObVUa/OhaTEvoYw3oM1ZTTT0LtYolofJYqnWiBOusc6qgMlK2rfk5kod7vDn33cSKwGhFcyVrrFCn2qxuvYUWCpK4Yo6Hj7KIjoqMi9yHLHXAAWIfAFNMlCdaUGjlHLWn757rBkbuQUDVH8HmB6Vc3J3sybTbiFmMDP1cEVo=
