---
# This role will install Kafka with Zookeeper in group 'kafka' in the environment inventory

- name: "pull the {{ docker_image_tag }} image of zookeeper"
  shell: "docker pull {{ docker_registry }}whisk/zookeeper:{{ docker_image_tag }}"
  when: docker_registry != ""

- name: (re)start zookeeper
  docker:
    name: zookeeper
    image: "{{ docker_registry }}whisk/zookeeper:{{ docker_image_tag }}"
    state: reloaded
    restart_policy: "{{ docker.restart.policy }}"
    log_driver: syslog
    ports:
      - "{{ zookeeper.port }}:2181"

# this is important but do not yet know why
- name: wait before checking if zookeeper is up
  pause:
    seconds: 2

- name: wait until the Zookeeper in this host is up and running
  action: shell echo ruok | nc -w 3 {{ inventory_hostname }} {{ zookeeper.port }}
  register: result
  until: (result.rc == 0) and (result.stdout == 'imok')
  retries: 12
  delay: 5

- name: "pull the {{ docker_image_tag }} image of kafka"
  shell: "docker pull {{ docker_registry }}whisk/kafka:{{ docker_image_tag }}"
  when: docker_registry != ""

- name: (re)start kafka
  docker:
    name: kafka
    image: "{{ docker_registry }}whisk/kafka:{{ docker_image_tag }}"
    state: reloaded
    restart_policy: "{{ docker.restart.policy }}"
    log_driver: syslog
    links:
      - "zookeeper:zookeeper"
    env:
      "EXPOSED_HOST": "{{ inventory_hostname }}"
    ports:
      - "{{ kafka.port }}:9092"
      - "{{ kafka.ras.port }}:8080"

- name: wait until the Kafka in this host is up and running
  uri:
    url: "http://{{ inventory_hostname }}:{{ kafka.ras.port }}/ready"
  register: result
  until: (result.status == 200) and (result.json.msg == 'yes')
  retries: 12
  delay: 5
