---
# Wipe transient databases. You should know what you are doing here.

# make sure we have whisk.properties because wipeTransientDBs.sh needs it
- include: writeWhiskProperties.yml

- name: deploy database
  local_action: shell "./wipeTransientDBs.sh" chdir="{{ openwhisk_home }}/tools/db"
