##########
# This is .travis.yml configuration file specifically for master and develop branch.
# The travis job should contains only unit and integration tests.
#
# To avoid this file from being overwritten by .travis.yml from other branches,
# please add the following to your local git config:
#   git config merge.ours.driver true
##########

branches:
  only:
    - master
    - develop

language: scala

scala:
  - 2.10.5

jdk:
  - oraclejdk8

addons:
    postgresql: "9.3"

sudo: false

env:
  global:
    - PIO_HOME=`pwd`

before_script:
# Download spark, hbase
  - mkdir vendors
  - wget http://d3kbcqa49mib13.cloudfront.net/spark-1.3.0-bin-hadoop2.4.tgz
  - tar zxfC spark-1.3.0-bin-hadoop2.4.tgz vendors
  - wget http://archive.apache.org/dist/hbase/hbase-1.0.0/hbase-1.0.0-bin.tar.gz
  - tar zxfC hbase-1.0.0-bin.tar.gz vendors

# Prepare pio environment variables
  - set -a
  - source conf/pio-env.sh.travis
  - set +a

# Create postgres database for PredictionIO
  - psql -c 'create database predictionio;' -U postgres
  - ./bin/travis/pio-start-travis

script:
# Run stylecheck
  - sbt scalastyle

# Run all unit tests
  - sbt test

after_script:
  - ./bin/travis/pio-stop-travis
