# A Travis CI configuration file.

sudo: required

language: scala
scala:
   - 2.11.6

services:
  - docker

env:
  global:
    - TERM=dumb

notifications:
  email: false
  slack:
    on_pull_requests: false
    secure: mNQOpPaYodmmFj/PuYQczN4IWPGk7oNZ5P+BWygeE6bpgLNs86JkCq+fX5FJXsfXmvUZ7jTsQAMrq1ctUHyN8CpcEfewrFjqZrnrWyNSWVfAH5UaXBxj3TuNSpS1N4edbjUN0/LmTdtb6XXHi1wXQ+3zpncU+YOugWn6Ak9eDtdaomYMdAd0uMdLgQBxif/DKM8TMiHKJvnspfOVXNCvOijvJ5fruDOxVx8LWaqFQ68OU9UOpuLiTFCAg36AKwOkaJE15Mkg0SAB550NpKP4oo6wcDWQuvKahB0M01QP08pFKTyJjoOij38MQUX92dJGmsDYlwRLBWYShY2oTdYkHmSyCJJvKE1o043+ebqs/l9RPxegSIbON2zKuI5amYN6jJQpCnkW1h/2pkYHvFyVED9ITQ3y6nZOlVvjmhheeh3K38z2JB1nR1U/l3aYqGLbLhcOu9D9ChL0d/8KLnmY+ddz0GIwphNrL8YnP7yDPBl1YxwQdMuW/xACD6H6BHPEIexCFfMsnZjLZspc+ZRj1fVfU432cr3+VxTernDdaP8l7vmZBfKuaLRsp44hhZV1ltrClSX62ZrlqcR2E9awzwofozWlUdIRx/luk7N3R65cIraiHqAw6UrdWqqs0tTHUymnjvyLNE6XRGjYa2Fpkaj760w8g5ECHc8SO59tHKI=

install: true

before_install:
  - ./tools/travis/setup.sh

script:
  - ./tools/travis/build.sh
